from pydantic import BaseModel, Field
from typing import Literal, List, Union


class QueryClassificationState(BaseModel):
    """
    Represents the classification of a user's query, including the enhanced query,
    type, confidence score, reasoning, and follow-up requirements.
    """

    original_query_enhanced: str = Field(
        ...,
        description="The enhanced version of the user's original query, rewritten for better clarity and understanding.",
    )

    query_type: Literal["command", "information", "both"] = Field(
        ..., description="The type of query."
    )

    confidence_score: float = Field(
        ..., ge=0, le=1, description="The confidence score of the classification."
    )

    classification_reasoning: str = Field(
        ..., description="The reasoning behind the classification decision."
    )

    requires_follow_up: bool = Field(
        default=False,
        description="Indicates if a follow-up question is needed for clarification.",
    )

    follow_up_reasoning: str = Field(
        default="",
        description="The reasoning for why a follow-up question is needed, if applicable.",
    )

    # generated_follow_up_response: str = Field(
    #     default=None,
    #     description="The response generated by the LLM for follow-up purposes, if applicable. It should be sent to the user to ask for clarification.",
    # )

class QueryClarificationState(BaseModel):
    is_clarification_needed: bool = Field(
        default=False, # do not put the word error
        description=(
            "Indicates if clarification is needed for the query. "
            "This should be set to true if there are critical missing details in the query or the user did not ask a clear question yet."
        ),
    )

    clarification_reasoning: str = Field(
        default="",
        description="The reasoning behind the need for clarification.",
    )

    generated_response: str = Field(
        default="",
        description=(
        "The response generated by the LLM to ask the user for clarification, if applicable. It should be sent to the user to ask for clarification. "
        "This field should be populated when is_clarification_needed is true."
    ),
    )

    finalized_enhanced_query: str = Field(
        default="",
        description=(
            "The finalized enhanced query after clarification. This should be populated when is_clarification_needed is false, meaning the query is already clear and does not require clarification. "
            "This field should contain an enhanced version of all the user's requests that is clear and ready for processing."
        ),
    )


class InformationStep(BaseModel):
    description: str = Field(
        ..., description="A human-readable description of the information to provide."
    )

class VariableDetails(BaseModel):
    variable_name: str = Field(
        ..., description="The name of the variable."
    )

    description: str = Field(
        ..., description="A clear and concise explanation of what this variable represents and how it should be used."
    )

class CommandStep(BaseModel):
    command: str = Field(
        ..., 
        description="The command to execute."
    )

    description: str = Field(
        ...,
        description="A short, human-readable explanation of what this command does.",
    )

    expected_output: str = Field(
        default="", description="What the command is expected to produce. If the command produce no output. set it as 'no output'"
    )

    safety_risk: Literal["low", "medium", "high"] = Field(
        ..., description="The safety risk level of executing this command."
    )

    input_variables: List[VariableDetails] = Field(
        default_factory=list,
        description=(
            "A list of input variables required for executing the command, along with their descriptions. "
            "If the command does not require any input variables, this should be an empty list."
        ),
    )

    output_variables: List[VariableDetails] = Field(
        default_factory=list,
        description=(
            "A list of output variables produced by executing the command, along with their descriptions. "
            "If the command does not produce any output variables, this should be an empty list."
        ),
    )

class Step(BaseModel):
    description: str = Field(
        ..., description="A human-readable description of the step."
    )

    step_type: Literal["information", "command"] = Field(
        ..., description="The type of the step, either 'information' or 'command'."
    )

    step_details: Union[InformationStep, CommandStep] = Field(
        ..., description="The details of the step, which can be either information details or command details based on the step type."
    )

class PlanningState(BaseModel):
    """
    Represents the execution plan generated for a user query.
    """

    fulfillment_summary: str = Field(
        default="",
        description=(
            "A high-level explanation of how the user's request will be fulfilled. "
            "This may describe reasoning steps, conceptual answers, or execution logic."
        ),
    )

    plan_steps: List[Step] = Field(
        default_factory=list,
        description=(
            "A list of steps that outline the plan for fulfilling the user's request. Each step includes a description, type (information or command), and relevant details. "
            "The steps should be ordered in the sequence they will be executed or fulfilled."
        ),
    )

    requires_follow_up: bool = Field(
        default=False,
        description=(
            "Indicates if the plan requires a follow-up question for clarification "
            "This field should be set to true if any required information for performing the plan is missing, and we need to ask the user for clarification before proceeding."
    ),
    )

    follow_up_reasoning: str = Field(
        default="",
        description=(
            "The reasoning for why a follow-up question is needed, if applicable. "
            "This should explain what information is missing and why it's necessary for executing the plan."),
    )

    # generated_follow_up_response: str = Field(
    #     default=None,
    #     description="The response generated by the LLM for follow-up purposes, if applicable. It should be sent to the user to ask for clarification."
    # )

class UserValidationState(BaseModel):
    user_feedback_type: Literal["approved", "rejected", "needs_clarification", "update_plan", "pending"] = Field(
        default="pending",
        description=(
            "The user's feedback on the generated plan after validation. " 
            "It can be 'approved' if the user approves the plan, "
            "'rejected' if the user rejects the plan, " 
            "'needs_clarification' if the user asks for clarification for the current plan without providing specific feedback on what needs to be clarified, " 
            "or 'update_plan' if the user provides specific feedback on what needs to be updated in the plan. " \
            "`pending` indicates that the user has not responded to the validation question yet, so we cannot proceed without the user's feedback on the plan."
        ),
    )

    user_feedback: List[str] = Field(
        default_factory=list,
        description=(
            "A list of specific feedback points provided by the user regarding what needs to be updated in the plan. "
            "This feedback would be used to update the current plan."
        ),
    )

    is_validation_required: bool = Field(
        default=False,
        description=(
            "Indicates whether validation process is finished and we can proceed to execute the plan or not. "
            "This should be set to true when the user approves the plan, or if the user rejects the plan but does not provide any specific feedback on what needs to be updated (in this case, we can consider the user's rejection as a disapproval of the current plan without asking for an updated plan, so we can end the validation process and proceed to generate a final response based on the user's disapproval). "
            "This should be set to false if the user asks for clarification or provides specific feedback on what needs to be updated, since in both cases we need to update the plan and ask for validation again until we get an approval or a rejection without specific feedback. "
            "This should also be set to false if the user did not respond to the validation question yet, since we cannot proceed without the user's feedback on the plan."
        ),
    )

    validation_reasoning: str = Field(
        default="",
        description=(
            "The reasoning behind why validation is required or not."
        ),
    )

    generated_response: str = Field(
        default="",
        description=(
            "The response generated by the LLM for user validation purposes. It should be sent to the user to validate the generated execution/information plan. "
            "If the user asked for clarification for the current plan, this field should contain a response to answer the user's clarification question. Otherwise, it should contain a response to validate the current plan without asking any clarification questions."
        ),
    )

class VariableExecutionContext(BaseModel):
    variable_name: str = Field(
        ..., description="The name of the variable."
    )

    description: str = Field(
        ..., description="A clear and concise explanation of what this variable represents in the context of command execution."
    )

    value: str = Field(
        ..., description="The value of the variable in the context of command execution after running."
    )

class ExecutionOrchestratorState(BaseModel):
    """ 
    Represents the state of the execution orchestrator, which is responsible for managing the execution of commands and information retrieval based on the generated plan.
    """
    next_step: Step = Field(
        ...,
        description=(
            "The next step to execute or fulfill, which is determined based on the generated plan and user validation feedback. This should be populated with the details of the next step, including its type (information or command) and relevant details for execution or fulfillment."
        ),
    )

    variable_execution_contexts: List[VariableExecutionContext] = Field(
        default_factory=list,
        description=(
          "A list of variable execution contexts that provide details about the output variables of command executions or information retrieval operations. "
          "This should be updated after each command execution or information retrieval to include the output variables produced by that step and their current values. If no steps have been executed yet or if the executed steps do not produce any output variables, this should be an empty list."
        ),
    )


class CommandExecution(BaseModel):
    command: str = Field(
        ..., description="The exact command-line instruction that was executed."
    )

    success: bool = Field(
        ..., description="Indicates whether the command executed successfully."
    )

    output: str = Field(
        ..., description="The standard output produced by the command, if any. If no output, set it as 'no output'."
    )

    error: str = Field(
        default="", description="The error output produced by the command, if any. If no errors, set it as 'no errors'."
    )
    # messages: Optional[List[str]] = Field(default_factory=list),
    # remaining_steps: Optional[List[str]] = Field(default_factory=list)

class InformationResponse(BaseModel):
    query: str = Field(
        default="",
        description="The query or topic that was answered"
    )
    
    answer: str = Field(
        default="",
        description="Clear and user-friendly explanation"
    )

class FinalResponse(BaseModel):
    """
    Final response sent to the user.
    """

    response: str = Field(
        ..., description="User-friendly final response combining all results"
    )

    summary: str = Field(
        default="",
        description="Short summary of what was done"
    )

class OSAssistantState(BaseModel):
    """
    Represents the state of the OS Assistant, including any relevant information
    about the current session, user preferences, and system status.
    """
    # ========== User query ==========

    turn_num: int = Field(
        default=1,
        description="A counter to keep track of the number of turns in the conversation.",
    )

    original_queries: List[str] = Field(
        default_factory=list,
        description=(
            "A list of the user's original queries. This should include the initial query and any follow-up queries that the user has made for clarification. The most recent query should be at the end of the list."
        ),
    )

    original_queries_enhanced: List[str] = Field(
        default_factory=list,
        description=(
            "A list of enhanced versions of the user's original queries, rewritten for better clarity and understanding."
        ),
    )

    finalized_enhanced_query: str = Field(
        default=None,
        description=(
            "The finalized enhanced query after any necessary clarifications. This should be the version of the user's query that is clear and ready for processing, incorporating any enhancements made during classification and clarification."
        ),
    )

    multi_turn_generated_responses: List[str] = Field(
        default_factory=list,
        description=(
            "A list of responses generated by the LLM during multi-turn interactions  "
        ),
    )

    # ========== Query Classification ==========

    query_classification: QueryClassificationState = Field(
        default=None, description="The classification of the user's query."
    )

    # This field should be updated by the parsing logic in the query classification node after receiving the response from the LLM
    # The generated response from the LLM must be in the format of QueryClassificationState, so we can directly assign it to this field
    # If an error occurs, retry and generate another response until we get a valid QueryClassificationState response or reach a maximum number of retries to avoid infinite loops
    query_classification_status: str = Field(
        default=None,
        description="The status of the query classification process (e.g., 'pending', 'completed', 'error').",
    )

    multi_turn_conversation_history: List[dict] = Field(
        default_factory=list,
        description=(
            "A list of dictionaries representing the multi-turn conversation history for query clarification. "
            "Each dictionary will have the following structure: {'turn_num': int, 'user_query': str, 'assistant_response': str}."
        ),
    )

    # ============ Follow-up query & Clarification ============

    # In case the original query requires a follow-up question for clarification
    clarification_attempts: int = Field(
        default=0,
        description="The number of attempts made to clarify the original query.",
    )

    query_clarification: QueryClarificationState = Field(
        default=QueryClarificationState(),
        description="The state of the query clarification process."
    )

    # =========== Planning ===========

    planning: PlanningState = Field(
        default=PlanningState(),
        description="The execution plan generated for the user's query, including information steps and command steps.",
    )

    planning_status: str = Field(
        default=None,
        description="The status of the planning process (e.g., 'pending', 'completed', 'error').",
    )
    
    # =========== User Validation ===========

    user_validation: UserValidationState = Field(
        default=UserValidationState(),
        description="The state of the user validation process for the generated plan."
    )

    user_validation_status: str = Field(
        default=None,
        description="The status of the user validation process (e.g., 'pending', 'completed', 'error')."
    )

    # =========== Execution & ExecutionOrchestrator ===========

    current_step_index: int = Field(
        default=0,
        description=(
            "The index of the current step being executed in the steps list of the PlanningState. This should be updated after each step execution to reflect the next step to execute. "
        )
    )

    total_steps: int = Field(
        default=0,
        description=(
            "The total number of steps in the plan that need to be executed. This should be set after the planning process is completed and should reflect the length of the steps list in the PlanningState."
        )
    )

    execution_orchestrator: ExecutionOrchestratorState = Field(
        default=None,
        description="The state of the execution orchestrator, which manages the execution of commands."
    )

    variable_execution_contexts: List[VariableExecutionContext] = Field(
        default_factory=list,
        description=(
            "A list of variable execution contexts that provide details about the output variables of command executions. "
            "This should be updated after each command execution to include the output variables produced by that command and their current values. If no commands have been executed yet or if the executed commands do not produce any output variables, this should be an empty list."
        ),
     )

    command_executions: List[CommandExecution] = Field(
        default_factory=list,
        description=(
            "A list of command execution results, detailing the outcome of each command "
            "that was run as part of fulfilling the user's request."
        ),
    )

    command_execution_status: str = Field(
        default=None,
        description="The status of the command execution process (e.g., 'pending', 'completed', 'error')."
    )

    # =========== Information Response ===========

    generated_information_responses: List[InformationResponse] = Field(
        default_factory=list,
        description="A list of generated responses to answer the information the user requested"
    )

    generated_information_responses_status: str = Field(
        default=None,
        description="The status of the information generation process (e.g., 'pending', 'completed', 'error')."
    )

    # =========== Final Response ===========
    generated_final_response: str = Field(
        default=None,
        description="The final response generated to be sent to the user after completing all steps of the plan execution. This should be a clear and user-friendly response"
    )

    final_response_status: str = Field(
        default=None,
        description="The status of the final response process (e.g., 'pending', 'completed', 'error')."
    )